### ISSUE TITLE
chnage date type

### ISSUE THREAD

**Issue by vahidalvandi** [Modulr/angular-bootstrap-datepicker#6]
hello
i need change Gregorian calendar to shamsi in asia where is core of calendar after change it all your module calendar  type

**Comment by alfredobarron** [comment]
mdr-angular-datepicker is based in [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) you can see in this url https://github.com/eternicode/bootstrap-datepicker/tree/master/js/locales if exist support this calendar
